package kickstart.orders;

public enum SubCategory {
	
	ABSAETZE, SOHLEN, KNOEPFE, NAEHTE, FLICKEN,

	SCHLUESSEL_KOPIEREN, SCHILDER_GRAVIEREN, WAESCHE, ANZUEGE,
	
	LEDER, KABEL_ERSETZEN, LOETEN, SCHEREN, MESSER_SCHAERFEN 

	
}
